<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'../css/style.css');
 echo $this->headLink()->appendStylesheet($this->baseUrl.'../js/extjs/resources/css/ext-all.css');
 echo $this->headScript()->appendFile($this->baseUrl.'../js/extjs/ext-all.js');
 echo $this->headScript()->appendFile($this->baseUrl.'../js/func.js');?>

<div id="menu">
<form action="<?php echo $this->baseUrl ?> user-manager/edit" method="post">
<div id="user" class="user"><h3>Users</h3>
<?php foreach ($users as $user) : ?>
      <input type="checkbox" name="<?php echo 'user'.$this->escapeHtml($user->id) ?>"  value="<?php echo $this->escapeHtml($user->id) ;?>" > <?php echo $this->escapeHtml($user->name);?> <Br>
       
<?php endforeach; ?>
</div>


<div id="educ" class="user"><h3>Education</h3>
<?php foreach ($educs as $educ) : ?>
      <input type="checkbox" name="<?php echo 'educ'.$this->escapeHtml($educ->id_user) ?>" value="<?php echo $this->escapeHtml($educ->id_user) ;?>" > <?php echo $this->escapeHtml($educ->education);?> <Br>
       
<?php endforeach; ?>
</div>


<div id="city" class="user"><h3>City</h3>
<?php foreach ($citys as $city) : ?>
      <input type="checkbox" name="<?php echo 'city'.$this->escapeHtml($city->id_user) ?>"  value="<?php echo $this->escapeHtml($city->id_user) ;?>" > <?php echo $this->escapeHtml($city->city);?> <Br>
       
<?php endforeach; ?>
</div>
<div class="no"></div>
<input type="submit" value="Показать" />
</form>
</div>
</Br>
<a href="<?php echo $this->url('users/upload-manager',
            array('action'=>'upload'));?>">&raquo Показать</a>