<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('TEST'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->baseUrl.'../js/extjs/resources/css/ext-all-neptune.css');
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
           ->appendFile($this->basePath().'/js/extjs/ext-all-debug.js')
           ->appendFile($this->basePath().'/js/func.js')
          ; ?>

    </head>
    <body>
      
            
       </nav> 
        <div class="container">
            <?php  echo $this -> content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php //echo $this->inlineScript() ?>
    </body>
</html>
